FROM achertovsky/php-infrastructure:base_fpm

ARG USER_ID=1000

RUN groupadd -g ${USER_ID} developer && \
    useradd -u ${USER_ID} -g developer -m -d /home/developer developer

COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN pecl install xdebug-3.4.0beta1 memprof

RUN docker-php-ext-enable opcache xdebug memprof

RUN cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini && \
    echo "short_open_tag=off" >> /usr/local/etc/php/php.ini

RUN echo "xdebug.mode=off" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini &&\
    echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini &&\
    echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini &&\
    echo "xdebug.client_port=9001" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

RUN echo "memprof.output_dir=/var/www/html/var" >> /usr/local/etc/php/php.ini

RUN apt install -y \
    htop \
    watch \
    vim \
    xq \
    wget \
    git

CMD ["php", "-r", "while (true) { sleep(3600); }"]
