FROM php:8.5

RUN apt update && apt install -y \
    libicu-dev \
    libzip-dev \
    unzip \
    curl \
    default-mysql-client \
    libjudy-dev

RUN docker-php-ext-install \
    intl \
    pdo \
    pdo_mysql \
    zip

WORKDIR /var/www/html
